version: "3.9"

services:
  app:
    build:
      context: .
      args:
          - DEV=false
    ports:
      - "8000:8000"
    volumes:
      - ./parking_lot:/parking_lot
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations && # This and migrate for each of testing.
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=default_pass
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment: # This is environment that will be pulled by os.environ in Python.
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=default_pass


volumes:
  dev-db-data:
