# Generated by Django 3.2.19 on 2023-05-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parking_place", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parkingplace",
            old_name="status",
            new_name="statusType",
        ),
        migrations.RenameField(
            model_name="parkingplace",
            old_name="vehicle_type",
            new_name="vehicleType",
        ),
    ]
