# Generated by Django 3.2.19 on 2023-05-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20230506_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplace',
            name='vehicle_type',
            field=models.TextField(choices=[('Motorcycle', 'Motorcycle'), ('Car', 'Car'), ('Van', 'Van')], max_length=10),
        ),
    ]
