# Generated by Django 3.2.19 on 2023-05-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_place', '0005_alter_parkingplace_vehicle_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusType',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
        migrations.AlterField(
            model_name='parkingplace',
            name='status',
            field=models.TextField(choices=[('Empty', 'Empty'), ('Adjacent', 'Adjacent'), ('Full', 'Full'), ('Van', 'Van')], max_length=8),
        ),
    ]
