# Generated by Django 3.2.19 on 2023-05-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_place', '0006_auto_20230507_2045'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parkingplace',
            table='parking_lot',
        ),
    ]
