# Generated by Django 3.2.19 on 2023-05-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_place', '0007_alter_parkingplace_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parkingplace',
            table=None,
        ),
    ]
